- name: variables from files
  hosts: local
  connection: local
  vars_files: #systematic way to load variables from files
  - course.yaml #to load the variables from the file course.yaml
  tasks:
  - name: print course info
    ansible.builtin.debug:
      msg: "Course Name is: {{ COURSE }}, Duration: {{ DURATION }}, Trainer: {{ Trainer }}"