- name: user creation
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: check user exist or not
    ansible.builtin.command: id roboshop # to check if the user roboshop exist or not, if the user exist it will return 0 and if the user does not exist it will return 1
    register: user_output
    ignore_errors: true

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ user_output }}"

  - name: create user
    ansible.builtin.command: useradd roboshop
    when: user_output.rc != 0